#!/usr/bin/env sh

set -e

if [ ! -d "$HOME/dotfiles" ]; then
  echo "Expected dotfiles repo to be cloned at $HOME/dotfiles. Aborting"
  exit 1
fi

link () {
  SRC=$1
  DST=$2

  if [ -e "$DST" ]; then
    echo "$DST already exists, not overwriting. If you want the one from dotfiles, move the old one out of the way and re-run setup"
  else
    echo "Linking $SRC -> $DST"
    ln -s "$SRC" "$DST"
  fi
}

mkdir -p "$HOME/.config"
mkdir -p "$HOME/.local/bin"

link "$HOME/dotfiles/vim" "$HOME/.config/nvim"
link "$HOME/dotfiles/alacritty" "$HOME/.config/alacritty"
link "$HOME/dotfiles/tmux.conf" "$HOME/.tmux.conf"
link "$HOME/dotfiles/bash_profile" "$HOME/.bash_profile"
link "$HOME/dotfiles/bash_profile" "$HOME/.bashrc"
link "$HOME/dotfiles/inputrc" "$HOME/.inputrc"

link "$HOME/dotfiles/bin/dev" "$HOME/.local/bin/dev"

git submodule init
git submodule update

FORMULAS=""

add_formula() {
  FORMULA=$1

  if ( brew list $FORMULA >> /dev/null ); then
    echo "Looks like $FORMULA is installed, skipping it"
  else
    FORMULAS="$FORMULAS $FORMULA"
  fi
}

add_formula tmux
add_formula nvim
add_formula ripgrep
add_formula abduco

if [ "$FORMULAS" != "" ]; then
  brew install $FORMULAS
fi

brew tap caskroom/fonts && brew cask install font-source-code-pro

nvim -c ':PlugInstall | :qa'
