#!/usr/bin/env sh

set -e

if [ ! -d "$HOME/dotfiles" ]; then
  echo "Expected dotfiles repo to be cloned at $HOME/dotfiles. Aborting"
  exit 1
fi

./setup-scripts/apt_packages
./setup-scripts/configure_git
./setup-scripts/docker
./setup-scripts/pip_packages
./setup-scripts/rustup-init.sh
./setup-scripts/link_configs
./setup-scripts/vimstone
./setup-scripts/install_fonts
./setup-scripts/upterm
./setup-scripts/obsidian
./setup-scripts/manual_reminders
