#!/usr/bin/env sh

set -e

# Allow rootless docker through apparmor. Taken from
# https://docs.docker.com/engine/security/rootless/
filename=$(echo $HOME/bin/rootlesskit | sed -e s@^/@@ -e s@/@.@g)

cat <<EOF > ~/${filename}
abi <abi/4.0>,
include <tunables/global>

"$HOME/bin/rootlesskit" flags=(unconfined) {
  userns,

  include if exists <local/${filename}>
}
EOF
sudo mv ~/${filename} /etc/apparmor.d/${filename}
sudo systemctl restart apparmor.service
