#!/usr/bin/env sh

set -e

sudo apt install \
  git \
  fish \
  ripgrep \
  jq \
  libxml2-utils \
  tmux \
  nodejs \
  python3-pip \
  python3-full \
  uidmap \
  fzf \
  xclip \
  fuse3 \
  curl \
  flatpak

