#!/usr/bin/env sh

set -e

mkdir -p ~/.local/bin
curl -L \
  https://github.com/helix-editor/helix/releases/download/25.07.1/helix-25.07.1-x86_64.AppImage \
  -o ~/.local/bin/hx
chmod 755 ~/.local/bin/hx
