#!/usr/bin/env sh

set -e


FORMULAS=""

add_formula() {
  FORMULA=$1

  if ( brew list $FORMULA >> /dev/null ); then
    echo "Looks like $FORMULA is installed, skipping it"
  else
    FORMULAS="$FORMULAS $FORMULA"
  fi
}

add_formula tmux
add_formula nvim
add_formula ripgrep
add_formula abduco

if [ "$FORMULAS" != "" ]; then
  brew install $FORMULAS
fi

brew tap caskroom/fonts && brew cask install font-source-code-pro
