#!/usr/bin/env sh

set -e

link () {
  SRC=$1
  DST=$2

  if [ -e "$DST" ]; then
    echo "$DST already exists, not overwriting. If you want the one from dotfiles, move the old one out of the way and re-run setup"
  else
    echo "Linking $SRC -> $DST"
    ln -s "$SRC" "$DST"
  fi
}

mkdir -p "$HOME/.config"
mkdir -p "$HOME/.config/fish"

link "$HOME/dotfiles/alacritty" "$HOME/.config/alacritty"
link "$HOME/dotfiles/zellij" "$HOME/.config/zellij"
link "$HOME/dotfiles/helix" "$HOME/.config/helix"
link "$HOME/dotfiles/tmux.conf" "$HOME/.tmux.conf"
link "$HOME/dotfiles/config.fish" "$HOME/.config/fish/config.fish"

