#!/usr/bin/env sh

echo "Here are some urls for installations steps to manually perform"
echo ""
echo https://golang.org/doc/install
echo https://github.com/alacritty/alacritty/blob/master/INSTALL.md
echo https://github.com/owenthereal/upterm#from-source
echo https://cloud.google.com/sdk/docs/install
echo https://brave.com/linux/
echo https://slack.com/downloads/linux
echo https://support.zoom.us/hc/en-us/articles/204206269-Installing-or-updating-Zoom-on-Linux
