#!/usr/bin/env sh

set -e

mkdir -p ~/.local/bin
curl -L https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage -o ~/.local/bin/nvim
chmod 755 ~/.local/bin/nvim

git clone git@github.com:flipstone/vimstone.git ~/.config/nvim

nvim -c ':PlugInstall | :qa'
