#!/usr/bin/env sh

set -e

curl -L https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage -o ~/.local/bin/nvim
chmod 755 ~/.local/bin/nvim

git clone git@github.com:flipstone/vimstone.git ~/.config/nvim

nvim -c ':PlugInstall | :qa'
